### ISSUE TITLE
Implement support for configuration files instead of command line parameters

### ISSUE THREAD

**Issue by rmchamberlain** [scitran/reaper#2]
Preference for format of config file?  JSON?

**Comment by gsfr** [comment]
We recently dropped config file support throughout scitran. Too opaque/redundant/cumbersome. Why not just use a one-line bash script? Regarding your question, there is a standard for [python config files](https://docs.python.org/2/library/configparser.html).

**Comment by rmchamberlain** [comment]
I expect every site to want some slightly different behavior from the reaper, so I'm afraid of the command line options getting too cumbersome, but I'm find tabling it until a config file is an obviously better solution, if ever.

**Comment by gsfr** [comment]
Sounds good.
For the record, I don't see much of a difference between a config file and command line arguments. Programmatically, both parsers return some kind of config object. And for the user, a bash script with one argument per line seems just as good as a separate file.
We used to try to handle both, with command line agreements taking precedence over the config file, and that turn out to be rather cumbersome and error-prone.
