### ISSUE TITLE
Tilde character not supported in path parameter for folder_sniper 

### ISSUE THREAD

**Issue by ryansanford** [scitran/reaper#32]
Below command silently fails. Changing `path` to an absolute path allowed the same data to store.

```
folder_sniper --insecure "~/Desktop/Flywheel_Import/" "https://localhost:8443/api?secret=bogus-secret"
```

**Comment by gsfr** [comment]
The quotes around the path prevent the shell from expanding the tilde. I'll add that. And I'll also add an error message in case the given path does not exist.
