### ISSUE TITLE
Start Unit Tests

### ISSUE THREAD

**Issue by rmchamberlain** [scitran/reaper#4]

**Comment by gsfr** [comment]
Arguably, a command line utility, such as the reaper, should be tested as such, and not by trying to fit it into a given unit test framework. A separate python script that sets up a DICOM server and an upload server and then runs the reaper might be the way to go. What do you think about that?

**Comment by rmchamberlain** [comment]
I think testing as a command line utility is a proper system level test, and we should do that, but I don't think that removes the benefit of having true unit level tests.  I do plan to implement tests of individual functions where appropriate - that sort of testing has been very helpful for me in my other projects.

**Comment by kofalt** [comment]
:+1: 

Eventual integration tests that set up a fake server and get scanned will be great, but involving server processes & network is both complex, and hard to cover all cases. For example the various servers we've tried have each behaved differently from each other & from actual scanners.

My assumption has been that (at some point) we'll have both a networked integration test, some local tests that just use saved assets of some kind, and possibly unit tests that don't even touch disk. How useful each of these might be and what order they should be constructed is up for discussion.
