### ISSUE TITLE
Eliminate scitran.data dependency

### ISSUE THREAD

**Issue by gsfr** [scitran/reaper#5]
What do you think about dropping support for peripheral data reaping, which would allow us to drop the dependency on scitran/data. All we currently have is semi-acurate code for reaping GE physio data.

Getting scanner physio data into the system is rather important, though, so we need another plan. The current code still gets it wrong on occasion, because of GE’s crazy, headerless way of recording physio. Might be best/easiest to put a human in charge.

**Comment by rmchamberlain** [comment]
Let's discuss this live - I don't think I fully understand the situation.

**Comment by gsfr** [comment]
Instead of dropping peripheral data reaping altogether, we should work to eliminate the scitran.data dependency, but with out eliminating this feature.

gephysio.py makes use of scitran.data for retrieving a number of scitran-specific attributes from both dicoms and pfiles. Severing this dependency would imply a fair amount of redundant code unless some of this complexity can be shifted to the reaper altogether.

**Comment by gsfr** [comment]
This has largely been achieved, although `gephysio` is currently unusable. Separate ticket filed (#15).
