### ISSUE TITLE
Add EEG reaper

### ISSUE THREAD

**Issue by ambrussimon** [scitran/reaper#59]
Add EEG reaper

- Identify how group/project/subject/session-uid/acquisition-uid should be _"encoded"_
    - Current plan:
        - group/project/subject ~ directory structure
        - session/acquisition ~ filename prefix
- Implement new reaper
- Add tests

**Comment by larsoner** [comment]
I did some work on an MEG / EEG reaper using MNE-Python (since it reads many MEG and EEG formats already). Maybe you can use or modify that.
