### ISSUE TITLE
Should be POST for upload?

### ISSUE THREAD

**Issue by xoltar** [scitran/reaper#9]
Looking at reaper.py, starting around line 239 in master, it looks like reaper uses URIs from its configuration for upload, and then looking at http_upload, it appears to upload all its files to the same URI using PUT. If it's going to use the same URI for everything, it should be POST, not PUT, no? PUT means "here's some data, put it exactly HERE". So either the method should be POST, or if PUT is desired, reaper should be making up unique URIs for each file. Right? Am I missing something?

**Comment by gsfr** [comment]
We are basically trying to follow standard [REST semantics](https://en.wikipedia.org/wiki/Representational_state_transfer#Applied_to_web_services) in our API, but the "receive file and figure out where it goes" case is not really covered by those. That said, I would be inclined to agree with you, reaper uploads should be a POST. I'll make the change on both ends as soon as I get to it.
